### ISSUE TITLE
starting.txt

### ISSUE THREAD

**Issue by ghost** [Jeffdemongo/DBD_Dataset#1]
def start():
    """
    Captures video feed frame by frame, crops out unecessary dino and processes
    """
    startingpoint_obj = open('D:/DBD_ML/starting.txt','r')
    startingpoint = int(startingpoint_obj.read())
    startingpoint_obj.close()
    sct = mss()

I don't know what 'starting.txt' is.

**Comment by Jeffdemongo** [comment]
Starting.txt was just a text file with the number of frame where it left of
is stored in with no special formatting or anything

Kaktow ***@***.***> schrieb am Mi., 14. Juli 2021, 14:05:

**Comment by Jeffdemongo** [comment]
It was a way for me to capture frames over multiple sessions without having
to start over again and without having to change variables in the script
manually

Kaktow ***@***.***> schrieb am Mi., 14. Juli 2021, 14:05:

**Comment by ghost** [comment]
Traceback (most recent call last):
  File "C:\Users\whlsl\Desktop\Download\DBD_Dataset-master\capture_feed.py", line 127, in <module>
    start()
  File "C:\Users\whlsl\Desktop\Download\DBD_Dataset-master\capture_feed.py", line 17, in start
    startingpoint_obj = open('‪C:/Users/whlsl/Desktop/Download/DBD_Dataset-master/starting.txt','r')
OSError: [Errno 22] Invalid argument: '\u202aC:/Users/whlsl/Desktop/Download/DBD_Dataset-master/starting.txt'

I can't figure out why this error is happening.

**Comment by Jeffdemongo** [comment]
It could be because you have to run the script as administrator. I usually started the cmd as admin and then activated my env and ran the script from there. If that doesn't work I will have to take a look at what else could be causing it.

**Comment by Jeffdemongo** [comment]
A temporary fix would be to just set the starting frame variable manually (to 0 when you start the first recording session)
